export const NOTIFICATION_STRINGS = {
  page: {
    title: 'Notificaciones',
    markAllRead: 'Marcar todas como leídas',
    filterAll: 'Todas',
    filterUnread: 'No leídas',
    filterRead: 'Leídas',
    empty: 'Sin notificaciones',
    emptySubtitle: 'Aquí aparecerán las notificaciones de nuevos pedidos y reseñas.',
    emptyUnread: 'Estás al día',
    emptyUnreadSubtitle: 'No tienes notificaciones sin leer.',
    emptyRead: 'Sin notificaciones leídas',
    emptyReadSubtitle: 'Las notificaciones que leas aparecerán aquí.',
    settingsTitle: 'Preferencias de notificaciones',
  },
  card: {
    markRead: 'Marcar como leída',
    justNow: 'Justo ahora',
    minutesAgo: (n: number) => `hace ${n} minuto${n === 1 ? '' : 's'}`,
    hoursAgo: (n: number) => `hace ${n} hora${n === 1 ? '' : 's'}`,
    daysAgo: (n: number) => `hace ${n} día${n === 1 ? '' : 's'}`,
  },
  order: {
    customizationBadge: 'Personalización',
    customizationBanner: 'Requiere personalización',
    productsLabel: 'Productos',
    totalLabel: 'Total',
    shippingLabel: 'Envío a',
    unitPrice: 'c/u',
    customizationAccept: 'Aceptar personalización',
    customizationReject: 'Rechazar',
    customizationAccepted: 'Personalización aceptada',
    customizationRejected: 'Personalización rechazada',
    customizationRejectionPlaceholder: 'Motivo del rechazo...',
    customizationRejectionSubmit: 'Confirmar rechazo',
    customizationRejectionCancel: 'Cancelar',
    customizationDetailsLabel: 'Personalización',
    viewDetailsText: 'Ver detalles del pedido',
  },
  review: {
    priorityBadge: 'Reseña negativa',
    priorityBanner: 'Reseña prioritaria — calificación baja',
    productLabel: 'Producto',
    ratingLabel: 'Calificación',
    clientLabel: 'Cliente',
    moderateAction: 'Moderar reseña',
  },
  preferences: {
    orderNotificationsLabel: 'Recibir notificaciones de nuevos pedidos',
    reviewNotificationsLabel: 'Recibir notificaciones de nuevas reseñas',
    saving: 'Guardando...',
    saved: 'Guardado',
    savedToast: 'Cambio guardado',
    errorToast: 'No se pudo guardar el cambio',
    error: 'Error al guardar',
    loading: 'Cargando preferencias...',
  },
  toast: {
    newOrder: 'Nuevo pedido recibido',
    customizationBadge: 'Personalización',
    newReview: 'Nueva reseña de producto',
    priorityBadge: 'Reseña negativa',
  },
  errors: {
    fetchError: 'No se pudieron cargar las notificaciones',
  },
} as const;
