import type { UnitOfMeasure } from '@/lib/types/inventory.types';

export const UNIT_OF_MEASURE_LABELS: Record<UnitOfMeasure, string> = {
  grams: 'Gramos',
  kilograms: 'Kilogramos',
  milliliters: 'Mililitros',
  liters: 'Litros',
  units: 'Unidades',
};

export const UNIT_OF_MEASURE_OPTIONS = (
  Object.entries(UNIT_OF_MEASURE_LABELS) as [UnitOfMeasure, string][]
).map(([value, label]) => ({ value, label }));

export const INVENTORY_STRINGS = {
  page: {
    title: 'Gestión de Inventario',
    subtitle: 'Registra y administra los insumos de materia prima.',
  },
  form: {
    title: 'Registrar insumo',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej: Harina de trigo',
    unitLabel: 'Unidad de medida',
    unitPlaceholder: 'Selecciona una unidad',
    stockLabel: 'Cantidad inicial',
    stockPlaceholder: '0',
    submitButton: 'Registrar insumo',
    submittingButton: 'Registrando...',
  },
  edit: {
    title: 'Editar insumo',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej: Harina de trigo',
    unitLabel: 'Unidad de medida',
    stockLabel: 'Stock actual (solo lectura)',
    saveButton: 'Guardar cambios',
    savingButton: 'Guardando...',
    cancelButton: 'Cancelar',
    unitChangeWarning:
      'Advertencia: cambiar la unidad de medida puede afectar la interpretación del stock y el historial de movimientos existentes.',
  },
  history: {
    title: 'Historial de movimientos',
    backButton: '← Volver al inventario',
    stockLabel: 'Stock actual',
    filterTypeLabel: 'Tipo',
    filterTypeAll: 'Todos los movimientos',
    filterTypeEntry: 'Solo entradas',
    filterTypeConsumption: 'Solo consumos',
    filterDateFrom: 'Desde',
    filterDateTo: 'Hasta',
    colDate: 'Fecha y hora',
    colType: 'Tipo',
    colQuantity: 'Cantidad',
    colPreviousStock: 'Stock anterior',
    colNewStock: 'Stock nuevo',
    colReference: 'Referencia',
    colAdmin: 'Administrador',
    typeEntry: 'Entrada',
    typeConsumption: 'Consumo',
    emptyMessage: 'No hay movimientos que coincidan con los filtros.',
    historyButton: 'Historial',
  },
  consumption: {
    title: 'Registrar consumo de insumos',
    openButton: 'Registrar consumo',
    referenceLabel: 'Referencia (opcional)',
    referencePlaceholder: 'Ej: Lote #001 - Torta de chocolate',
    dateLabel: 'Fecha de consumo',
    supplyLabel: 'Insumo',
    supplyPlaceholder: 'Selecciona un insumo',
    quantityLabel: 'Cantidad',
    quantityPlaceholder: '0',
    addItemButton: '+ Agregar insumo',
    removeItemButton: 'Quitar',
    submitButton: 'Registrar consumo',
    submittingButton: 'Registrando...',
    cancelButton: 'Cancelar',
  },
  entry: {
    title: 'Registrar entrada de insumo',
    supplyLabel: 'Insumo',
    supplyPlaceholder: 'Selecciona un insumo',
    quantityLabel: 'Cantidad a ingresar',
    quantityPlaceholder: '0',
    dateLabel: 'Fecha de entrada',
    submitButton: 'Registrar entrada',
    submittingButton: 'Registrando...',
  },
  list: {
    emptyMessage: 'No hay insumos registrados.',
    colName: 'Nombre',
    colUnit: 'Unidad',
    colStock: 'Stock actual',
    colStatus: 'Estado',
    colActions: 'Acciones',
    editButton: 'Editar',
  },
  validation: {
    nameRequired: 'El nombre es obligatorio',
    nameMax: 'El nombre no puede superar los 100 caracteres',
    unitRequired: 'Selecciona una unidad de medida',
    stockMin: 'La cantidad inicial no puede ser negativa',
    supplyRequired: 'Selecciona un insumo',
    entryQuantityMin: 'La cantidad debe ser mayor a cero',
    consumptionQuantityMin: 'La cantidad debe ser mayor a cero',
    dateRequired: 'La fecha es obligatoria',
    itemsRequired: 'Agrega al menos un insumo',
  },
  errors: {
    duplicateName: 'Ya existe un insumo con ese nombre',
    createError: 'No se pudo registrar el insumo',
    updateError: 'No se pudo actualizar el insumo',
    fetchError: 'No se pudieron cargar los insumos',
    historyError: 'No se pudo cargar el historial',
    entryError: 'No se pudo registrar la entrada',
    consumptionError: 'No se pudo registrar el consumo',
    stockInsufficient: 'Stock insuficiente para uno o más insumos',
  },
  success: {
    created: 'Insumo registrado correctamente',
    entryCreated: 'Entrada registrada correctamente',
  },
} as const;
