import type { UnitOfMeasure } from '@/lib/types/inventory.types';

export const INVENTORY_CONFIG = {
  POLL_INTERVAL_MS: 60_000,
};

export const UNIT_OF_MEASURE_LABELS: Record<UnitOfMeasure, string> = {
  grams: 'Gramos',
  kilograms: 'Kilogramos',
  milliliters: 'Mililitros',
  liters: 'Litros',
  units: 'Unidades',
};

export const UNIT_OF_MEASURE_VALUES = [
  'grams',
  'kilograms',
  'milliliters',
  'liters',
  'units',
] as const satisfies readonly UnitOfMeasure[];

export const UNIT_OF_MEASURE_OPTIONS = (
  Object.entries(UNIT_OF_MEASURE_LABELS) as [UnitOfMeasure, string][]
).map(([value, label]) => ({ value, label }));

export const INVENTORY_STRINGS = {
  page: {
    title: 'Gestión de Inventario',
    subtitle: 'Registra y administra los insumos de materia prima.',
  },
  form: {
    openButton: 'Registrar insumo',
    title: 'Registrar insumo',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej: Resina epóxica',
    unitLabel: 'Unidad de medida',
    unitPlaceholder: 'Selecciona una unidad',
    stockLabel: 'Cantidad inicial',
    stockPlaceholder: '0',
    submitButton: 'Registrar insumo',
    submittingButton: 'Registrando...',
    cancelButton: 'Cancelar',
  },
  edit: {
    title: 'Editar insumo',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej: Resina epóxica',
    unitLabel: 'Unidad de medida',
    stockLabel: 'Stock actual (solo lectura)',
    thresholdLabel: 'Umbral mínimo de alerta',
    thresholdPlaceholder: '0',
    thresholdHint: 'El sistema alertará cuando el stock llegue a esta cantidad. Con 0, solo recibirás alerta si el insumo se agota por completo.',
    saveButton: 'Guardar cambios',
    savingButton: 'Guardando...',
    cancelButton: 'Cancelar',
    unitChangeWarning:
      'Advertencia: cambiar la unidad de medida puede afectar la interpretación del stock y el historial de movimientos existentes.',
  },
  report: {
    title: 'Reporte de consumo de insumos',
    backButton: '← Volver al inventario',
    reportButton: 'Ver reporte',
    generating: 'Generando...',
    dateFromLabel: 'Desde',
    dateToLabel: 'Hasta',
    generateButton: 'Generar reporte',
    colSupply: 'Insumo',
    colUnit: 'Unidad',
    colStockInicial: 'Stock inicial',
    colEntradas: 'Entradas',
    colConsumo: 'Consumo',
    colStockFinal: 'Stock final',
    emptyMessage: 'No hay movimientos en el período seleccionado.',
    rendimientoTitle: 'Rendimiento estimado por referencia',
    rendimientoDisclaimer:
      'Nota: el rendimiento es un estimado basado en los consumos con referencia registrados en el período seleccionado. No refleja mermas, desperdicios ni ajustes manuales.',
    colReference: 'Referencia / Lote',
    colIngredient: 'Insumo',
    colQty: 'Cantidad consumida',
    noRendimiento: 'No hay consumos con referencia de producto en este período.',
    dateRequired: 'Selecciona un rango de fechas para generar el reporte.',
  },
  alerts: {
    sectionTitle: 'Alertas de stock',
    outOfStock: 'Sin stock',
    lowStock: 'Stock bajo',
    stockLabel: 'Stock',
    thresholdLabel: 'Umbral',
    avgDailySalesLabel: 'Consumo diario',
    daysRemainingLabel: 'Días restantes',
    daysRemainingUnknown: 'N/D',
    registerEntryButton: 'Registrar entrada',
  },
  history: {
    title: 'Historial de movimientos',
    backButton: '← Volver al inventario',
    clearFilters: 'Limpiar filtros',
    stockLabel: 'Stock actual',
    filterTypeLabel: 'Tipo',
    filterTypeAll: 'Todos los movimientos',
    filterTypeEntry: 'Solo entradas',
    filterTypeConsumption: 'Solo consumos',
    filterDateFrom: 'Desde',
    filterDateTo: 'Hasta',
    loadingMessage: 'Cargando...',
    colDate: 'Fecha y hora',
    colType: 'Tipo',
    colQuantity: 'Cantidad',
    colPreviousStock: 'Stock anterior',
    colNewStock: 'Stock nuevo',
    colReference: 'Referencia',
    colAdmin: 'Administrador',
    typeEntry: 'Entrada',
    typeConsumption: 'Consumo',
    emptyMessage: 'No hay movimientos que coincidan con los filtros.',
    historyButton: 'Historial',
  },
  consumption: {
    title: 'Registrar consumo de insumos',
    openButton: 'Registrar consumo',
    referenceLabel: 'Referencia (opcional)',
    referencePlaceholder: 'Ej: Lote #001 - Torta de chocolate',
    dateLabel: 'Fecha de consumo',
    supplyLabel: 'Insumo',
    supplyPlaceholder: 'Selecciona un insumo',
    quantityLabel: 'Cantidad de consumo',
    quantityPlaceholder: '0',
    addItemButton: '+ Agregar insumo',
    removeItemButton: 'Quitar',
    submitButton: 'Registrar consumo',
    submittingButton: 'Registrando...',
    cancelButton: 'Cancelar',
    stockAvailableLabel: 'Stock disponible:',
  },
  entry: {
    openButton: 'Registrar entrada',
    title: 'Registrar entrada de insumo',
    supplyLabel: 'Insumo',
    supplyPlaceholder: 'Selecciona un insumo',
    quantityLabel: 'Cantidad a ingresar',
    quantityPlaceholder: '0',
    dateLabel: 'Fecha de entrada',
    addItemButton: '+ Agregar insumo',
    removeItemButton: 'Quitar',
    submitButton: 'Registrar entrada',
    submittingButton: 'Registrando...',
    cancelButton: 'Cancelar',
  },
  list: {
    emptyMessage: 'No hay insumos registrados.',
    colName: 'Nombre',
    colUnit: 'Unidad',
    colStock: 'Stock actual',
    colStatus: 'Estado',
    colActions: 'Acciones',
    editButton: 'Editar',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
  },
  shared: {
    itemLabel: 'Insumo',
  },
  validation: {
    nameRequired: 'El nombre es obligatorio',
    nameMax: 'El nombre no puede superar los 100 caracteres',
    unitRequired: 'Selecciona una unidad de medida',
    stockMin: 'La cantidad inicial no puede ser negativa',
    thresholdMin: 'El umbral no puede ser negativo',
    supplyRequired: 'Selecciona un insumo',
    entryQuantityMin: 'La cantidad debe ser mayor a cero',
    consumptionQuantityMin: 'La cantidad debe ser mayor a cero',
    dateRequired: 'La fecha es obligatoria',
    itemsRequired: 'Agrega al menos un insumo',
  },
  errors: {
    duplicateName: 'Ya existe un insumo con ese nombre',
    createError: 'No se pudo registrar el insumo',
    updateError: 'No se pudo actualizar el insumo',
    fetchError: 'No se pudieron cargar los insumos',
    historyError: 'No se pudo cargar el historial',
    reportError: 'No se pudo generar el reporte',
    entryError: 'No se pudo registrar la entrada',
    consumptionError: 'No se pudo registrar el consumo',
    stockInsufficient: 'Stock insuficiente para uno o más insumos',
  },
  success: {
    created: 'Insumo registrado correctamente',
    entryCreated: 'Entrada registrada correctamente',
  },
  creationHint: {
    title: 'Insumo registrado correctamente.',
    body: 'Te recomendamos configurar un umbral mínimo de alerta desde la opción Editar del insumo. Si lo dejás en 0, el sistema solo te avisará cuando el stock llegue exactamente a cero — no antes.',
    editNow: 'Editar ahora',
    dismiss: 'Entendido',
  },
} as const;
